### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by zhaochl** [meteorchenwu/meteor#2]
java -Xms1024m -Xmx1024m -cp /data/src/meteor/jetty-server/target/meteor-jetty-server-1.0-SNAPSHOT-jar-with-dependencies.jar com.meteor.jetty.server.JettyServer "/data/src/meteor/mc/target/meteor-mc-1.0-SNAPSHOT.war" "/" "8070"

Error: Could not find or load main class com.meteor.jetty.server.JettyServer

**Comment by meteorchenwu** [comment]
已修复
